version: '3.8'

services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

  broker:
    build:
      context: broker
      dockerfile: Dockerfile
    restart: always

  publisher:
    build:
      context: publisher
      dockerfile: Dockerfile
    environment:
      - API_HOST=api
      - API_PORT=80
      - BROKER_HOST=broker
      - BROKER_PORT=1883
    depends_on:
      - api
      - broker
    restart: on-failure

  subscriber:
    build:
      context: subscriber
      dockerfile: Dockerfile
    environment:
      - BROKER_HOST=broker
      - BROKER_PORT=1883
    depends_on:
      - broker
    restart: on-failure

